version: "3.3"
services:
# if using prox/remoteurl then open /etc/docker/daemon.json and add the following ( not offline mode ! )
# {
#   "registry-mirrors": ["http://localhost:5001"],
#   "insecure-registries" : ["localhost:5000"]
# }
# and then restart docker 
# sudo systemctl restart docker
  registry:
    container_name: "registry"
    restart: always
    ports:
      - 5000:5000
    image: registry:2
    volumes: # see options https://docs.docker.com/registry/configuration/
      - "./docker-registry-config.yml:/etc/docker/registry/config.yml"
      - registry_cache:/var/lib/registry
volumes:
  registry_cache:
    driver: local
